### ISSUE TITLE
For a React-Native RN 0.60 app, do we still need to do install step: react-native link?

### ISSUE THREAD

**Issue by norby3** [react-native-community/react-native-push-notification-ios#21]
# Question 
I'm building a new app using RN 0.60.  The release notes for RN 0.60 say: "Most scenarios will not require the use of react-native link anymore."   

These install instructions say to run: 
react-native link @react-native-community/push-notification-ios

Is it still necessary?  Is there an alternate step?  (e.g. cd ios then run "pod install") 
Should we be doing the manual linking steps as shown here:  https://facebook.github.io/react-native/docs/pushnotificationios  

Thanks.

**Comment by johndturn** [comment]
I was getting an error when running my app b/c I manually ran the `react-native link`, which brought me here. 

I just manually unlinked the package, rebuilt, and tested, and it appears that it's working just fine. No need to manually link. The documentation just needs to be updated to show this.

**Comment by norby3** [comment]
Thanks @johndturn 
Am struggling to get local notifications working.   First focus is iOS.  
My goal is to have local notifications when the app is in either foreground or background.  

What combination of npm packages and/or tutorials did you follow?  

Am using these sources but trying to sort out the different instructions is challenge:  
https://github.com/zo0r/react-native-push-notification
https://github.com/react-native-community/react-native-push-notification-ios
https://facebook.github.io/react-native/docs/pushnotificationios
https://medium.com/differential/how-to-setup-push-notifications-in-react-native-ios-android-30ea0131355e
https://riptutorial.com/react-native/example/29845/push-notification-simple-setup

Also looked into the wix notification package but didn't try it.

**Comment by johndturn** [comment]
@norby3 Good question. Sounds like yours and my use cases are different, but related. I'm looking to integrate push notifications into our app for remote notifications, no plans for local notifications at this time. 

We're currently using the `react-native-push-notification` library, which also uses the `react-native-push-notification-ios` library as well, similar to you. 

When it comes to documentation and walkthroughs, I've used the documentation for the two above-mentioned libraries, from their respective `README`s. I haven't necessarily needed any other tutorials or walkthroughs yet, since we're still in early-days for this app, and we're working on other things in parallel. I've only used tutorials to gauge which libraries are the most popular, and best choice for implementing push notifications at this point in time. 

However, in looking at what you've linked to above, I do have one suggestion: It looks like you might be referencing out-of-date documentation. Since RN moves so fast, and has changed so drastically in the past year or so, I've been specifically configuring my search engine to only show articles written in the past year or less. 

If you're using Google, this looks like this: 

<img width="1132" alt="Screen Shot 2019-09-03 at 9 58 37 AM" src="https://user-images.githubusercontent.com/10634270/64184935-de4fc580-ce31-11e9-9246-83a1c8eea308.png">

Hope this helps!

**Comment by norby3** [comment]
thanks @johndturn!  like that google filter idea and agree that RN is changing so fast. 
the key for me was to understand that (on iOS) the local notifications will only work when scheduled and when the app is in the background.

**Comment by njdullea** [comment]
These are the steps I followed to install this package in RN 0.60+:

- yarn add @react-native-community/push-notification-ios
- cd ios
- pod install
- add the app delegate information (see getting started)


Hope this helps.

**Comment by Naturalclar** [comment]
For React Native 0.60+, `react-native link` is not required any more.
Instead, you'll need to run `cd ios && pod install` , as @njdullea says in the comment. Thanks :)
